use miden_objects::Felt;

// This file is generated by build.rs, do not modify manually.
// It is generated by extracting errors from the masm files in the `miden-lib/asm` directory.
//
// To add a new error, define a constant in masm of the pattern `const.ERR_<CATEGORY>_...`.
// Try to fit the error into a pre-existing category if possible (e.g. Account, Prologue,
// Non-Fungible-Asset, ...).

// NOTE SCRIPT ERRORS
// ================================================================================================

/// Error Message: "P2IDR's reclaimer is not the original sender"
pub const ERR_P2IDR_RECLAIM_ACCT_IS_NOT_SENDER: Felt = Felt::new(4026305220785643652);
/// Error Message: "P2IDR can not be reclaimed as the transaction's reference block is lower than the reclaim height"
pub const ERR_P2IDR_RECLAIM_HEIGHT_NOT_REACHED: Felt = Felt::new(4939276033581053863);
/// Error Message: "P2IDR scripts expect exactly 3 note inputs"
pub const ERR_P2IDR_WRONG_NUMBER_OF_INPUTS: Felt = Felt::new(15442560246661499708);

/// Error Message: "P2ID's target account address and transaction address do not match"
pub const ERR_P2ID_TARGET_ACCT_MISMATCH: Felt = Felt::new(16775440430394368057);
/// Error Message: "P2ID script expects exactly 2 note inputs"
pub const ERR_P2ID_WRONG_NUMBER_OF_INPUTS: Felt = Felt::new(8756972089530547977);

/// Error Message: "SWAP script requires exactly 1 note asset"
pub const ERR_SWAP_WRONG_NUMBER_OF_ASSETS: Felt = Felt::new(9499166029088338856);
/// Error Message: "SWAP script expects exactly 10 note inputs"
pub const ERR_SWAP_WRONG_NUMBER_OF_INPUTS: Felt = Felt::new(17502539132897750974);

pub const NOTE_SCRIPT_ERRORS: [(Felt, &str); 7] = [
    (ERR_P2IDR_RECLAIM_ACCT_IS_NOT_SENDER, "P2IDR's reclaimer is not the original sender"),
    (ERR_P2IDR_RECLAIM_HEIGHT_NOT_REACHED, "P2IDR can not be reclaimed as the transaction's reference block is lower than the reclaim height"),
    (ERR_P2IDR_WRONG_NUMBER_OF_INPUTS, "P2IDR scripts expect exactly 3 note inputs"),

    (ERR_P2ID_TARGET_ACCT_MISMATCH, "P2ID's target account address and transaction address do not match"),
    (ERR_P2ID_WRONG_NUMBER_OF_INPUTS, "P2ID script expects exactly 2 note inputs"),

    (ERR_SWAP_WRONG_NUMBER_OF_ASSETS, "SWAP script requires exactly 1 note asset"),
    (ERR_SWAP_WRONG_NUMBER_OF_INPUTS, "SWAP script expects exactly 10 note inputs"),
];
