name: "Task"
description: "Work item"
body:
  - type: markdown
    attributes:
      value: |
        A task should be less than a week worth of work!
  - type: textarea
    id: task-what
    attributes:
      label: "What should be done?"
      placeholder: "Add healthchecking to the servers"
    validations:
      required: true
  - type: dropdown
    id: workitem
    attributes:
      label: "Workitem"
      options:
        - Documentation
        - Refactoring
        - Tests
    validations:
      required: true
  - type: textarea
    id: task-how
    attributes:
      label: "How should it be done?"
      placeholder: "Add a /health endpoint to each of the servers, that returns a small JSON reponse and `200` while the service is healthy"
    validations:
      required: true
  - type: textarea
    id: task-done
    attributes:
      label: "When is this task done?"
      placeholder: "The task is done when the services are deployed with healthcheck"
    validations:
      required: true
  - type: textarea
    id: task-related
    attributes:
      label: "Additional context"
      description: "Add context to the tasks. E.g. other related tasks or relevant dicussions on PRs/chats."
    validations:
      required: false
