#!/bin/bash
#
###############
# Remove miden-prover installs
##############
sudo rm -f /lib/systemd/system/miden-prover.*
sudo rm -rf /opt/miden/miden-prover/
sudo deluser miden-prover
sudo systemctl daemon-reload
