#!/bin/bash
#
# This is a postinstallation script so the service can be configured and started when requested.

# user is expected by the systemd service file and `/opt/<user>` is its working directory,
sudo adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent miden-prover

# Working folder.
if [ -d "/opt/miden-prover" ]
then
    echo "Directory /opt/miden-prover exists."
else
    mkdir -p /opt/miden-prover
    sudo chown -R miden-prover /opt/miden-prover
fi

# Configuration folder
if [ -d "/etc/opt/miden-prover" ]
then
    echo "Directory /etc/opt/miden-prover exists."
else
    mkdir -p /etc/opt/miden-prover
    sudo chown -R miden-prover /etc/opt/miden-prover
fi

sudo systemctl daemon-reload
