#!/bin/bash
#
# This is a postinstallation script so the service can be configured and started when requested.

# user is expected by the systemd service file and `/opt/<user>` is its working directory,
sudo adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent miden-prover

# Working folder.
work="/opt/miden-prover"
sudo chown -R miden-prover "$work"

# Configuration folder
conf="/lib/systemd/system/miden-prover.service.d/debian.conf"
sudo chown -R miden-prover "$conf"

sudo systemctl daemon-reload
