#!/bin/bash
#
###############
# Remove miden-prover-proxy installs
##############
sudo rm -f /etc/systemd/system/miden-prover-proxy.service
sudo rm -rf /opt/miden/miden-prover-proxy/
sudo rm -rf /etc/opt/miden/miden-prover-proxy/
sudo deluser miden-prover-proxy
sudo systemctl daemon-reload
