#!/bin/bash
#
# This is a postinstallation script so the service can be configured and started when requested.

# User is expected by the systemd service file and `/opt/<user>` is its working directory,
sudo adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent miden-prover-proxy

work="/opt/miden-prover-proxy"
sudo chown -R miden-prover-proxy "$work"

sudo systemctl daemon-reload
sudo systemctl enable miden-prover-proxy
sudo systemctl start miden-prover-proxy
