[package]
name = "miden-proving-service"
version = "0.10.0"
description = "Miden blockchain proving service"
readme = "README.md"
keywords = ["miden", "proving", "service"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[[bin]]
name = "miden-proving-service"
path = "src/main.rs"

[features]
default = ["concurrent"]
concurrent = ["miden-tx/concurrent"]

[dependencies]
async-trait = "0.1"
axum = { version = "0.8" }
bytes = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }
miden-block-prover = { workspace = true, default-features = false }
miden-lib = { workspace = true, default-features = false }
miden-objects = { workspace = true, default-features = false, features = ["std"] }
miden-tx = { workspace = true, default-features = false, features = ["std"] }
miden-tx-batch-prover = { workspace = true, default-features = false, features = ["std"] }
opentelemetry = { version = "0.29", features = ["metrics", "trace"] }
opentelemetry-otlp = { version = "0.29", features = ["grpc-tonic"] }
opentelemetry_sdk = { version = "0.29", features = ["metrics", "rt-tokio"] }
opentelemetry-semantic-conventions = "0.29"
prometheus = "0.14"
prost = { version = "0.13", default-features = false, features = ["derive"] }
pingora = { version = "0.5", features = ["lb"] }
pingora-core = "0.5"
pingora-proxy = "0.5"
pingora-limits = "0.5"
reqwest = { version = "0.12" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_qs = { version = "0.15" }
tokio = { version = "1.44", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
thiserror = { workspace = true }
tonic = { version = "0.12", default-features = false, features = [
    "codegen",
    "prost",
    "transport",
] }
tonic-health = { version = "0.12" }
tonic-web = { version = "0.12" }
tracing = { version = "0.1" }
tracing-opentelemetry = "0.30"
tracing-subscriber = { version = "0.3", features = ["fmt", "json", "env-filter"] }
uuid = { version = "1.16", features = ["v4"] }

[dev-dependencies]
miden-lib = { workspace = true, default-features = false, features = ["testing"] }
miden-objects = { workspace = true, default-features = false, features = ["testing"] }
miden-tx = { workspace = true, default-features = false, features = ["testing"] }
miden-testing = { workspace = true, default-features = false }

[build-dependencies]
miette = { version = "7.5", features = ["fancy"] }
prost = { version = "0.13", default-features = false, features = ["derive"] }
prost-build = { version = "0.13" }
protox = { version = "0.8" }
tonic-build = { version = "0.12" }
