{
 "title": "PROXY",
 "time": { "from": "2024-12-19T14:36:56.711Z", "to": "2024-12-19T14:38:02.492Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests/m",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "increase(request_count[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total request count per worker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "worker_request_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Worker availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "worker_availability", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request failure count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "request_failure_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests/m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "targets": [
    { "expr": "increase(request_count[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queue size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "queue_size", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 7 },
   "targets": [
    { "expr": "worker_utilization", "legendFormat": "__auto" },
    { "expr": "queue_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate limit violations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate_limit_violations", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request latency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(request_latency_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}