[book]
authors = ["Miden contributors"]
description = "Description and core structures for the Miden protocol"
language = "en"
multilingual = false
title = "The Miden protocol"

[output.html]
git-repository-url = "https://github.com/0xMiden/miden-base"

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
